# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Run a one-line script
        run: echo Hello, it's a test job!

  deploy:
    runs-on: ubuntu-latest
    needs: [test]  
    steps:
      - name: Run a one-line script
        run: echo Deploying the project!
