name: CI/CD Pipeline-for testing

on:
  push:
    branches: [ "dev", "QA", "prod" ]
  pull_request:
    branches: [ "dev", "QA", "prod" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Build
        run: echo "Building the project for branch ${{ github.ref_name }}..."

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: ./  # Adjust this path to your build directory

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Tests
        run: echo "Running tests for branch ${{ github.ref_name }}..."

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/QA' || github.ref == 'refs/heads/prod'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: ./  # Adjust this as needed

      - name: Deploy to Environment
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/QA" ]]; then
            echo "Deploying to QA environment..."
          elif [[ "${{ github.ref }}" == "refs/heads/prod" ]]; then
            echo "Deploying to Production..."
          fi
