name: CI/CD Pipeline-for testing

on:
  push:
    branches: [ "dev", "qa", "main" ]
  pull_request:
    branches: [ "dev", "qa", "main" ]
  workflow_dispatch:

jobs:
  # CI: Build and Test
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Step
        run: echo "Building the project..."

  test:
    runs-on: ubuntu-latest
    needs: [build]  # Runs after build succeeds
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run tests
        run: echo "Running tests... (Replace this with actual test commands)"

  # CD: Deploy only if Build & Test succeed
  deploy-dev:
    runs-on: ubuntu-latest
    needs: [test]  
    if: github.ref == 'refs/heads/dev'  # Deploy only for the dev branch
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to Dev Environment
        run: echo "Deploying to Dev..."

  deploy-qa:
    runs-on: ubuntu-latest
    needs: [test]  
    if: github.ref == 'refs/heads/qa'  # Deploy only for the QA branch
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to QA Environment
        run: echo "Deploying to QA..."

  deploy-prod:
    runs-on: ubuntu-latest
    needs: [test]  
    if: github.ref == 'refs/heads/main'  # Deploy only for the main branch (Prod)
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to Prod Environment
        run: echo "Deploying to Production..."
